# Generated by Django 5.2 on 2025-05-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
