# Generated by Django 5.2 on 2025-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100),
        ),
    ]
