# Generated by Django 5.2 on 2025-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementApp', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
