# Generated by Django 5.2 on 2025-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementApp', '0003_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100),
        ),
    ]
